runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: main.app

 # - url: /.*
 #  script: test.app

libraries:
- name: MySQLdb
  version: "latest"
- name: numpy
  version: latest
- name: ssl
  version: latest

# [START env]
env_variables:
  MYSQL_USER: "root"
  MYSQL_PASSWORD: "root"
  MYSQL_DATABASE: "KRADB"
  # e.g. my-awesome-project:us-central1:my-cloud-sql-instance
  INSTANCE_CONNECTION_NAME: "abirafirst-153906:asia-east1:chatbotdb"
# [END env]

# [START cloudsql_settings]
beta_settings:
  # The connection name of your instance, available by using
  # 'gcloud beta sql instances describe [INSTANCE_NAME]' or from
  # the Instance details page in the Google Cloud Platform Console.
  cloud_sql_instances: abirafirst-153906:asia-east1:chatbotdb
# [END cloudsql_settings]
# [END app_yaml]